### ISSUE TITLE
Couldn't run on Taichi 0.8.9

### ISSUE THREAD

**Issue by taichiCourse01** [theYiran/Taichi_Procedure_Painting#1]
Hi @theYiran, could you give me the environment and Taichi version you run?

The GUI doesn't show anything on my ubuntu 21.04 PC. 
```
[Taichi] version 0.8.9, llvm 10.0.0, commit 0a391960, linux, python 3.8.11
[Taichi] Starting on arch=cuda
...
```

**Comment by theYiran** [comment]
[Taichi] version 0.7.32, llvm 10.0.0, commit 6652f94f, win, python 3.8.9
[Taichi] Starting on arch=cuda

Sorry just saw your message, hope it was not too late.

**Comment by theYiran** [comment]
I just realized that you need to press SPACE  to trigger the animation. Sorry for the unconvinance.

**Comment by theYiran** [comment]
I just realized that you need to press SPACE to trigger the animation. Sorry for the inconvenience.
